export const AllTechnologies = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Angular",
  "Vue.js",
  "SASS",
  "LESS",
  "SCSS",
  "TypeScript",
  "Webpack",
  "Git",
  "npm",
  "Yarn",
  "REST API",
  "Responsive Web Design (RWD)",
  "CSS Frameworks",
  "Package Managers",
  "Browser Developer Tools",
  "Frontend Testing",
  "Node.js",
  "Express.js",
  "Django",
  "Ruby on Rails",
  "ASP.NET",
  "Laravel",
  "Spring Boot",
  "Flask",
  "Phoenix",
  "GraphQL",
  "MongoDB",
  "MySQL",
  "PostgreSQL",
  "Firebase",
  "Redis",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Amazon Web Services (AWS)",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Sketch",
  "Figma",
  "InVision",
  "Zeplin",
  "Adobe XD",
  "Typography",
  "Color Theory",
  "Wireframing",
  "Prototyping",
  "User Interface (UI) Design",
  "User Experience (UX) Design",
  "Web Accessibility",
  "Graphic Design Principles",
  "Vector Graphics",
  "Image Optimization",
  "Mobile-First Design",
  "Design Systems",
  "Brand Identity Design",
  "Print Design",
  "Animation",
  "Interaction Design",
  "Usability Testing",
  "Design Thinking",
  "Visual Design",
  "Layout Design",
  "GitHub",
  "GitLab",
  "Bitbucket",
  "Travis CI",
  "CircleCI",
  "TeamCity",
  "Ansible",
  "Puppet",
  "Chef",
  "Terraform",
  "AWS CloudFormation",
  "Google Cloud Deployment Manager",
  "Microsoft Azure Resource Manager",
  "Monitoring and Logging Tools (e.g., Prometheus, Grafana, ELK Stack)",
  "Infrastructure as Code (IaC)",
  "Continuous Integration (CI)",
  "Continuous Deployment (CD)",
  "Container Orchestration",
  "Microservices Architecture",
  "Load Balancing",
  "Auto Scaling",
  "Serverless Computing",
  "Security and Compliance in DevOps",
  "Version Control",
  "Automated Testing",
  "Scripting (e.g., Bash, Python)",
  "Infrastructure Monitoring",
  "Incident Management",
  "Performance Optimization",
  "Collaboration and Communication Tools (e.g., Slack, Microsoft Teams)",
];
